### PR TITLE
Changes to app creation API

### PR DESCRIPTION
**Pull request by epwalsh**

### CODE REVIEW

**Comment by epwalsh** [comment]
Current failure comes from https://github.com/tokio-rs/tokio/issues/2965

**Review by Abhishek8394 — APPROVED** [review]
LGTM

**Comment by epwalsh** [comment]
Okay, I think I'm going to move forward with this PR since I like the idea of removing the `static` lifetime requirement on `Celery` apps, and also not having to use `OnceCell` and hack around its non-async-ness.

In this PR I will also update `tokio` (and `tokio-amqp`).

Still TODO:
- [ ] Fix tests.
- [ ] Make `CeleryBuilder::build` return `Result<Arc<Celery<..>>, ..>`.
- [ ] Pass `tokio` runtime to `app!` and through to the `CeleryBuilder` and `BrokerBuilder` so that it can be accessed by the `lapin::ConnectionProperties` `tokio-amqp` extension.
- [ ] Make similar changes to `beat` module and `beat!` macro.
- [ ] Update app and beat examples.
- [ ] Document breaking changes / upgrade guide in CHANGELOG.

**Comment by epwalsh** [comment]
These are pretty big changes to I'd like to get some other opinions. Mainly about the new API. For example, look at the diff for `examples/celery_app.rs`.

@crash-g @Keruspe

**Comment by crash-g** [comment]
Basically we are trading a `static` requirement for an explicit runtime initialization by the user. It's a tradeoff in my opinion, since initializing Celery needs a little more boilerplate, but I like the explicitness of this solution and overall I think it's better.

Also, I'm not sure how feasible it is, but could this pave the way to a runtime-agnostic crate? (this would be really good)

**Comment by epwalsh** [comment]
> Also, I'm not sure how feasible it is, but could this pave the way to a runtime-agnostic crate? (this would be really good)

I agree this would be great. At the moment I'm not sure about how many of the things we use from `tokio` internally would work with another runtime, but it would be fairly straightforward to replace many of them.

The things from `tokio` that we use throughout the library are:

- `tokio::sync::{RwLock, Mutex}` -> Here are a few alternatives: https://www.reddit.com/r/rust/comments/f4zldz/i_audited_3_different_implementation_of_async/
- `tokio::mpsc::*` -> Could be replaced with `flume`
- `tokio::select` -> Could be replaced with `futures::select`, although I've tried that before and had deadlocks for some reason. That was a while ago though. Maybe it will work now.
- `tokio::signal::unix::*` -> Could maybe use this crate instead: https://docs.rs/signal-hook/0.1.16/signal_hook/

**Comment by Abhishek8394** [comment]
Does this mean that we cannot use `#[tokio::main]` anymore?

**Comment by epwalsh** [comment]
> Does this mean that we cannot use `#[tokio::main]` anymore?

Yes, unfortunately 😭

**Comment by epwalsh** [comment]
This would not be an issue if we went with `async-std`, however, instead of `tokio`, i.e. we could use `#[async_std::main]`.

**Comment by Abhishek8394** [comment]
I see, it is the way lapin requires `Runtime` for init. I guess it can't be helped then.

**Comment by epwalsh** [comment]
> I see, it is the way lapin requires `Runtime` for init.

Right.

I just updated the CHANGELOG with an example of how you'd have to modify your code for these changes: https://github.com/rusty-celery/rusty-celery/pull/195/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by Keruspe** [comment]
> I see, it is the way lapin requires `Runtime` for init. I guess it can't be helped then. 

Lapin doesn't require it per se, tokio-amqp does, because tokio0.3 removed Handle::current()

**Comment by Keruspe** [comment]
Note that there are discussions of bringing it back, so this change would not be needed anymore

**Comment by Keruspe** [comment]
tokio-amqp 0.3.0 released based on tokio 0.3.4

**Comment by epwalsh** [comment]
Thanks @Keruspe!

**Pull request merged**
