### PR TITLE
Add support for cron schedules

### PR DESCRIPTION
**Pull request by crash-g**
# Description

This MR is a proposal for the implementation of cron schedules. It adds a `CronSchedule` struct which supports the same syntax supported by [crontab schedules in Celery](https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html#crontab-schedules).

## Usage example

```rust
let cron_schedule = CronSchedule::from_string("*/5 8-17 * * *")?;
```

# Implementation approach

There is a good crate that implements support for cron expressions in Rust ([GitHub link](https://github.com/zslayton/cron)). Supporting cron schedules using that crate would be trivial.

However, this MR proposes a scratch implementation, mainly for a couple of reasons:
- to reduce the number of dependencies
- to support Celery syntax (I could not find discrepancies so far but this does not mean there cannot be, since cron syntax is not entirely standardized)

## Comparison with cron crate

1. We do not use `nom` to parse cron expressions: it seemed a little overkill to introduce the dependency since the syntax to parse is fairly simple
2. We optimize full ranges: cron stores a B-tree set with all the elements, while we only store a placeholder when the range has no holes (this is also mentioned as a future optimization in that crate)
3. The algorithm that finds the next time to run a schedule is the same, apart some cosmetic changes
4. We do not support seconds and years in our schedules: this is coherent with what Celery does in Python

# What is left to do

If the proposal is accepted, some things should be done before merging:

- Improve syntax support
  + support shorthands (e.g. `@yearly`)
  + support strings for months and weekdays (e.g. `jan` or `mon`)
- Improve user errors when parsing
- Add documentation
- Add more tests

### CODE REVIEW

**Comment by epwalsh** [comment]
This would be great to have! Seems like your cron implementation is pretty simple so far, so I'm all for doing that in-house instead of adding another dependency. But if for some reason it starts growing a lot in complexity, I'm not opposed to adding the `cron` crate. We could also put the entire `beat` module and it's dependency behind feature flag. Then I wouldn't feel too bad about adding more deps.

**Comment by crash-g** [comment]
I think that as you say the implementation is sufficiently simple and that if we ever change our mind it's extremely easy to throw this module away and replace it with the `cron` crate. Hence if you agree I will now polish this branch to prepare it for the merge.

As for the feature flag I do not have a strong opinion but it may be worth to add it regardless.

**Comment by epwalsh** [comment]
@crash-g great, let's move forward with it then. For now I don't think we should worry about adding a feature flag for beat. At least until we start adding more beat-specific dependencies.

**Comment by crash-g** [comment]
Hi @epwalsh, I think this MR is ready to be merged, please have a look when you have time.

**Comment by epwalsh** [comment]
@crash-g awesome! I am off tomorrow so I may not get a chance to look at it until Monday

**Comment by epwalsh** [comment]
Hey @crash-g, this looks great.

One comment I have is with file organization. Right now, within `src/beat/`, there is `schedule.rs` and then a folder `scheduler/`. Why not rename `schedule.rs` to `schedule/mod.rs`? I think that would be more consistent with how the rest of the project is organized.

**Comment by crash-g** [comment]
Done!

**Review by epwalsh — APPROVED** [review]
Looks great!

**Pull request merged**
