### PR TITLE
Bumps Tokio dependencies to latest version

### PR DESCRIPTION
**Pull request by pastre**
his PR is focused mainly on getting the latest version of Lapin and Tokio running on the project. I'm a rust newbie and I'm not sure if my solution is the best and would be very happy to get some feedback!

### CODE REVIEW

**Comment by Miezhiko** [comment]
I think there were few pull requests doing same (also can drop tokio-ampq dep I think)

**Comment by pastre** [comment]
@Miezhiko closed the other PRs and removed tokio-amqp

**Comment by pastre** [comment]
@epwalsh would love to get your feedback on this! It's small :)

**Review by epwalsh — APPROVED** [review]
LGTM, thanks @pastre!

**Comment by Miezhiko** [comment]
@epwalsh I think this project has big potential, strongly suggest creating an organization for it and adding few people (including lapin maintainer) to be able to accept pull requests, I personally want it to grow healthy.

**Comment by epwalsh** [comment]
I would love the help. I've called for maintainers before but didn't get any takers. If anyone reading this is interesting, please reach out.

**Comment by binderman** [comment]
I am using it, so I would like to help.

**Comment by Miezhiko** [comment]
ping @Keruspe

**Pull request merged**
