### PR TITLE
Change redis delivery msg to comply with python message

### LINKED ISSUE #225: Redis broker python compatibility
Using redis broker, i tried consuming task sent from python example. The worker crashed while deserializing the message:
```
[2021-01-03T12:44:34Z INFO  celery::app] Consuming from ["celery", "buggy-queue"]
[2021-01-03T12:44:34Z ERROR celery::app] Deserialize error "invalid type: string "W1syLCAyXSwge30sIHsiY2FsbGJhY2tzIjogbnVsbCwgImVycmJhY2tzIjogbnVsbCwgImNoYWluIjogbnVsbCwgImNob3JkIjogbnVsbH1d", expected a sequence at line 1 column 119"
Error: broker error

Caused by:
    0: Deserialize error "invalid type: string "W1syLCAyXSwge30sIHsiY2FsbGJhY2tzIjogbnVsbCwgImVycmJhY2tzIjogbnVsbCwgImNoYWluIjogbnVsbCwgImNob3JkIjogbnVsbH1d", expected a sequence at line 1 column 119"
    1: invalid type: string "W1syLCAyXSwge30sIHsiY2FsbGJhY2tzIjogbnVsbCwgImVycmJhY2tzIjogbnVsbCwgImNoYWluIjogbnVsbCwgImNob3JkIjogbnVsbH1d", expected a sequence at line 1 column 119
```

I took a look at the messages stored on redis.
Python message:
```
{
  "body": "W1syLCAyXSwge30sIHsiY2FsbGJhY2tzIjogbnVsbCwgImVycmJhY2tzIjogbnVsbCwgImNoYWluIjogbnVsbCwgImNob3JkIjogbnVsbH1d",
  "content-encoding": "utf-8",
  "content-type": "application/json",
  "headers": {
    "lang": "py",
    "task": "add",
    "id": "b2678b59-3618-4364-bee3-a4f0dcd53a83",
    "shadow": null,
    "eta": null,
    "expires": null,
    "group": null,
    "group_index": null,
    "retries": 0,
    "timelimit": [
      null,
      null
    ],
    "root_id": "b2678b59-3618-4364-bee3-a4f0dcd53a83",
    "parent_id": null,
    "argsrepr": "(2, 2)",
    "kwargsrepr": "{}",
    "origin": "gen54412@arch"
  },
  "properties": {
    "correlation_id": "b2678b59-3618-4364-bee3-a4f0dcd53a83",
    "reply_to": "cd67a8ea-639b-34af-b645-b3d03b4adb4a",
    "delivery_mode": 2,
    "delivery_info": {
      "exchange": "",
      "routing_key": "celery"
    },
    "priority": 0,
    "body_encoding": "base64",
    "delivery_tag": "eefdfa80-7ed3-4d87-9a51-12a7ffee14ec"
  }
}
```
Rust message:
```
{
  "body": [
91,91,93,44,123,34,120,34,58,49,44,34,121,34,58,50,125,44,123,34,99,97,108,108,98,97,99,107,115,34,58,110,117,108,108,44,34,101,114,114,98,97,99,107,115,34,58,110,117,108,108,44,34,99,104,97,105,110,34,58,110,117,108,108,44,34,99,104,111,114,100,34,58,110,117,108,108,125,93
],
  "content_encoding": "utf-8",
  "content_type": "application/json",
  "correlation_id": "ab1bb0ea-4c5e-4e86-aaa9-8906d2b3e932",
  "delivery_tag": "5271ed4d-c5c9-48bb-b0f5-331a7e3b1b10",
  "headers": {
    "argsrepr": null,
    "eta": null,
    "expires": null,
    "group": null,
    "id": "ab1bb0ea-4c5e-4e86-aaa9-8906d2b3e932",
    "kwargsrepr": null,
    "lang": null,
    "meth": null,
    "origin": "gen68757@arch",
    "parent_id": null,
    "retries": null,
    "root_id": null,
    "shadow": null,
    "task": "add",
    "timelimit": [
      null,
      null
    ]
  },
  "reply_to": null
}
```

The body seems to be base64 encoded, aside from that some fields are inside 'properties' object, and some are missing. For reference i took a look at the documentation https://docs.celeryproject.org/en/master/internals/protocol.html, but some things also differ in position compared to python payload e.g content-type and encoding.

I can provide PR adding base64 encoding, and moving fields to match python payload more closely, if that seems oke?

### PR DESCRIPTION
**Pull request by mkucijan**
This should resolve #225. I have also noticed #209, and i was thinking maybe to copy the code into TryFrom traits, and make Delivery redis only serialized message format maybe?

### CODE REVIEW

**Review by epwalsh — COMMENTED** [review]
Thanks @mkucijan! I just want to get a 2nd look from @Abhishek8394 before merging.

@Abhishek8394 can you review when you get a chance?

**Comment by epwalsh** [comment]
> I have also noticed #209, and i was thinking maybe to copy the code into TryFrom traits, and make Delivery redis only serialized message format maybe?

I'm okay with the (new) format of the `Delivery` struct, but I think the unified protocol type should still be called `Message`. So, basically, we'd just need to replace the existing `Message` and `MessageProperties` with what we have for `Delivery` and `DeliveryProperties`, respectively. Then update all of the code that deals with serializing and deserializing these types in `src/protocol/mod.rs` and `src/brokers/*.rs`.

**Review by Abhishek8394 — APPROVED** [review]
LGTM

**Review by epwalsh — APPROVED** [review]

**Comment by epwalsh** [comment]
Thanks @mkucijan!

**Pull request merged**
