### PR TITLE
Modify the beat macro to accept a list of tasks to schedule

### PR DESCRIPTION
**Pull request by crash-g**
## Chosen API

The implemented API is the following:

```rust
tasks = [
    "add" => {
        add,
        schedule = DeltaSchedule::new(Duration::from_secs(5)),
        args = (1, 2),
    },
    "long_running" => {
        long_running_task,
        schedule = CronSchedule::from_string("*/2 * * * *")?,
        args = (Some(1),),
    }
],
```

The `tasks` array is right before the `task_routes` array, as in the `app` macro.

## Comments

The modification to the `beat` macro unearthed a few problems that needed to be addressed.

First of all, the `CronScheduleError` was a standalone error, but it
is more useful to make it part of the `BeatError` family, so that
users may expect only one type of error when using the beat module.
This is also needed by our macro, that internally creates a function
which should return only one type of error (i.e., `BeatError`).

Another problem was that the `BeatBuilder`'s build method
produced a `CeleryError` instead of a `BeatError`, which was weird.
This was due to the call to `configure_task_routes` on the broker,
which in turn calls `Rule::new`.

There is no specific reason why `Rule::new` should produce a
`CeleryError`, so it now produces a `BadRoutingPattern` error which is
convertible to `BrokerError` which is convertible to both
`CeleryError` and `BeatError`.

Of course these are breaking changes, what do you think about this @epwalsh ?

## Other changes

- Another API change is the addition of `schedule_named_task` on the `Beat` struct. Compared to `schedule_task`, this method accepts a custom name instead of using the task name. I'm not sure about the method name, are there other suggestions?
- I have used intra doc links for the `beat` macro documentation. Is this alright? (for reference, it landed on stable with Rust 1.48.0)

### CODE REVIEW

**Comment by epwalsh** [comment]
These are definitely good changes!

> I have used intra doc links for the beat macro documentation. Is this alright?

Yeup! That's great. I tried to update the rest of the docs at some point to use intra doc links but may have missed a few places.

> Another API change is the addition of `schedule_named_task` on the Beat struct.

In what scenario would you use this method instead of just `schedule_task`? In other words, why would you want to use a different name for the task?

**Comment by crash-g** [comment]
> In what scenario would you use this method instead of just `schedule_task`? In other words, why would you want to use a different name for the task?

Actually I have a real use case from how we are using Celery in my company. We have a scheduled task that processes data and runs with a different schedule and arguments according to whether it is processing real-time data (every few hours) or historical data (every few days). I think this scenario is quite common and the name could be a good way to handle it.

To be fair, when I'll have the time to think a little better to a database-based scheduler the problem of identifiers will come up for sure. I'm tentatively thinking that this custom name may fill that need, but I will not be sure until I start working on that.

**Comment by crash-g** [comment]
Hi @epwalsh, if there aren't other comments this can be merged!

**Review by epwalsh — APPROVED** [review]
Looks great!

**Pull request merged**
